import { formatObject, FormatValue } from "../../src/js/d365ce";

test("FormatObject Test", () => {
  const account = {
      "@odata.context":
        "https://valmark.crm.dynamics.com/api/data/v9.0/$metadata#accounts/$entity",
      "@odata.etag": 'W/"4607103"',
      "address2_addresstypecode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      address2_addresstypecode: 1,
      "merged@OData.Community.Display.V1.FormattedValue": "No",
      merged: false,
      "statecode@OData.Community.Display.V1.FormattedValue": "Active",
      statecode: 0,
      "exchangerate@OData.Community.Display.V1.FormattedValue": "1.0000000000",
      exchangerate: 1,
      "openrevenue_state@OData.Community.Display.V1.FormattedValue": "1",
      openrevenue_state: 1,
      name: "Helen T. Orcutt",
      "opendeals@OData.Community.Display.V1.FormattedValue": "1",
      opendeals: 1,
      "modifiedon@OData.Community.Display.V1.FormattedValue":
        "10/18/2019 2:04 PM",
      modifiedon: "2019-10-18T18:04:51Z",
      "_owninguser_value@Microsoft.Dynamics.CRM.lookuplogicalname":
        "systemuser",
      _owninguser_value: "bfd1e1c2-774a-e911-a831-000d3a1a274b",
      address1_composite: "US",
      "accountratingcode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      accountratingcode: 1,
      "marketingonly@OData.Community.Display.V1.FormattedValue": "No",
      marketingonly: false,
      "donotphone@OData.Community.Display.V1.FormattedValue": "Allow",
      donotphone: false,
      "preferredcontactmethodcode@OData.Community.Display.V1.FormattedValue":
        "Any",
      preferredcontactmethodcode: 1,
      "_ownerid_value@OData.Community.Display.V1.FormattedValue": "Rex Tan",
      "_ownerid_value@Microsoft.Dynamics.CRM.associatednavigationproperty":
        "ownerid",
      "_ownerid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      _ownerid_value: "bfd1e1c2-774a-e911-a831-000d3a1a274b",
      "customersizecode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      customersizecode: 1,
      "donotpostalmail@OData.Community.Display.V1.FormattedValue": "Allow",
      donotpostalmail: false,
      "openrevenue_date@OData.Community.Display.V1.FormattedValue":
        "11/3/2019 3:41 PM",
      openrevenue_date: "2019-11-03T20:41:45Z",
      "openrevenue_base@OData.Community.Display.V1.FormattedValue": "$0.00",
      openrevenue_base: 0,
      "businesstypecode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      businesstypecode: 1,
      "donotemail@OData.Community.Display.V1.FormattedValue": "Allow",
      donotemail: false,
      "address2_shippingmethodcode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      address2_shippingmethodcode: 1,
      address1_addressid: "542a0b9a-3c98-47b6-9762-b5d18a123069",
      "address2_freighttermscode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      address2_freighttermscode: 1,
      vm_accountid: "3CA3B8D2-034B-E911-A82F-000D3A17CE77",
      "createdon@OData.Community.Display.V1.FormattedValue":
        "3/20/2019 7:32 AM",
      createdon: "2019-03-20T11:32:26Z",
      "opendeals_state@OData.Community.Display.V1.FormattedValue": "1",
      opendeals_state: 1,
      "openrevenue@OData.Community.Display.V1.FormattedValue": "$0.00",
      openrevenue: 0,
      "donotsendmm@OData.Community.Display.V1.FormattedValue": "Send",
      donotsendmm: false,
      "donotfax@OData.Community.Display.V1.FormattedValue": "Allow",
      donotfax: false,
      "donotbulkpostalmail@OData.Community.Display.V1.FormattedValue": "No",
      donotbulkpostalmail: false,
      address1_country: "US",
      "versionnumber@OData.Community.Display.V1.FormattedValue": "4,607,103",
      versionnumber: 4607103,
      "creditonhold@OData.Community.Display.V1.FormattedValue": "No",
      creditonhold: false,
      telephone1: "1",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue":
        "US Dollar",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty":
        "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname":
        "transactioncurrency",
      _transactioncurrencyid_value: "bf87aaf6-d547-e911-a997-000d3a1abaad",
      accountid: "3ca3b8d2-034b-e911-a82f-000d3a17ce77",
      "donotbulkemail@OData.Community.Display.V1.FormattedValue": "Allow",
      donotbulkemail: false,
      "_modifiedby_value@OData.Community.Display.V1.FormattedValue": "Rex Tan",
      "_modifiedby_value@Microsoft.Dynamics.CRM.lookuplogicalname":
        "systemuser",
      _modifiedby_value: "bfd1e1c2-774a-e911-a831-000d3a1a274b",
      "followemail@OData.Community.Display.V1.FormattedValue": "Allow",
      followemail: true,
      "shippingmethodcode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      shippingmethodcode: 1,
      "_createdby_value@OData.Community.Display.V1.FormattedValue": "Rex Tan",
      "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      _createdby_value: "bfd1e1c2-774a-e911-a831-000d3a1a274b",
      "territorycode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      territorycode: 1,
      "statuscode@OData.Community.Display.V1.FormattedValue": "Active",
      statuscode: 1,
      "participatesinworkflow@OData.Community.Display.V1.FormattedValue": "No",
      participatesinworkflow: false,
      "accountclassificationcode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      accountclassificationcode: 1,
      "_owningbusinessunit_value@Microsoft.Dynamics.CRM.associatednavigationproperty":
        "owningbusinessunit",
      "_owningbusinessunit_value@Microsoft.Dynamics.CRM.lookuplogicalname":
        "businessunit",
      _owningbusinessunit_value: "c25fcf59-ac47-e911-a997-000d3a1abaad",
      address2_addressid: "1881680a-d8cf-457f-981c-63d16bffb3d1",
      "opendeals_date@OData.Community.Display.V1.FormattedValue":
        "11/3/2019 3:41 PM",
      opendeals_date: "2019-11-03T20:41:45Z",
      address2_line1: null,
      address1_telephone1: null,
      address1_postofficebox: null,
      marketcap: null,
      address1_name: null,
      emailaddress3: null,
      address1_telephone3: null,
      address2_county: null,
      numberofemployees: null,
      address1_line2: null,
      timespentbymeonemailandmeetings: null,
      yominame: null,
      address2_longitude: null,
      ownershipcode: null,
      timezoneruleversionnumber: null,
      primarysatoriid: null,
      _masterid_value: null,
      address2_fax: null,
      _slaid_value: null,
      aging60_base: null,
      accountcategorycode: null,
      entityimage: null,
      revenue: null,
      address1_postalcode: null,
      emailaddress1: null,
      address1_latitude: null,
      address1_telephone2: null,
      customertypecode: null,
      address2_telephone1: null,
      address2_name: null,
      accountnumber: null,
      address1_stateorprovince: null,
      address1_line3: null,
      industrycode: null,
      address1_line1: null,
      importsequencenumber: null,
      paymenttermscode: null,
      fax: null,
      address2_line3: null,
      address2_utcoffset: null,
      _modifiedonbehalfby_value: null,
      utcconversiontimezonecode: null,
      creditlimit: null,
      ftpsiteurl: null,
      stockexchange: null,
      address2_telephone3: null,
      _owningteam_value: null,
      aging60: null,
      _defaultpricelevelid_value: null,
      revenue_base: null,
      aging90: null,
      aging30: null,
      entityimage_url: null,
      sharesoutstanding: null,
      address2_latitude: null,
      stageid: null,
      preferredappointmenttimecode: null,
      address2_composite: null,
      aging90_base: null,
      address1_fax: null,
      _originatingleadid_value: null,
      address1_city: null,
      description: null,
      address2_stateorprovince: null,
      overriddencreatedon: null,
      teamsfollowed: null,
      _slainvokedid_value: null,
      address1_primarycontactname: null,
      onholdtime: null,
      _createdbyexternalparty_value: null,
      traversedpath: null,
      processid: null,
      _createdonbehalfby_value: null,
      _modifiedbyexternalparty_value: null,
      address2_postalcode: null,
      address1_shippingmethodcode: null,
      entityimage_timestamp: null,
      address1_upszone: null,
      address2_primarycontactname: null,
      primarytwitterid: null,
      _preferredserviceid_value: null,
      address2_city: null,
      _primarycontactid_value: null,
      address1_freighttermscode: null,
      address1_longitude: null,
      telephone2: null,
      address1_addresstypecode: null,
      lastusedincampaign: null,
      _preferredsystemuserid_value: null,
      address2_postofficebox: null,
      creditlimit_base: null,
      telephone3: null,
      preferredappointmentdaycode: null,
      websiteurl: null,
      sic: null,
      _preferredequipmentid_value: null,
      lastonholdtime: null,
      address2_line2: null,
      tickersymbol: null,
      entityimageid: null,
      aging30_base: null,
      _territoryid_value: null,
      address1_county: null,
      marketcap_base: null,
      address2_upszone: null,
      address2_country: null,
      address1_utcoffset: null,
      emailaddress2: null,
      _parentaccountid_value: null,
      address2_telephone2: null
    },
    newAccount = formatObject(account);

  expect(JSON.stringify(newAccount)).toBe(
    `{"owninguser":{"id":"bfd1e1c2-774a-e911-a831-000d3a1a274b","logicalName":"systemuser"},"ownerid":{"id":"bfd1e1c2-774a-e911-a831-000d3a1a274b","formatted":"Rex Tan","logicalName":"systemuser"},"transactioncurrencyid":{"id":"bf87aaf6-d547-e911-a997-000d3a1abaad","formatted":"US Dollar","logicalName":"transactioncurrency"},"modifiedby":{"id":"bfd1e1c2-774a-e911-a831-000d3a1a274b","formatted":"Rex Tan","logicalName":"systemuser"},"createdby":{"id":"bfd1e1c2-774a-e911-a831-000d3a1a274b","formatted":"Rex Tan","logicalName":"systemuser"},"owningbusinessunit":{"id":"c25fcf59-ac47-e911-a997-000d3a1abaad","logicalName":"businessunit"},"address2_addresstypecode":{"value":1,"formatted":"Default Value"},"merged":{"value":false,"formatted":"No"},"statecode":{"value":0,"formatted":"Active"},"exchangerate":{"value":1,"formatted":"1.0000000000"},"openrevenue_state":{"value":1,"formatted":"1"},"opendeals":{"value":1,"formatted":"1"},"modifiedon":{"value":"2019-10-18T18:04:51Z","formatted":"10/18/2019 2:04 PM"},"accountratingcode":{"value":1,"formatted":"Default Value"},"marketingonly":{"value":false,"formatted":"No"},"donotphone":{"value":false,"formatted":"Allow"},"preferredcontactmethodcode":{"value":1,"formatted":"Any"},"customersizecode":{"value":1,"formatted":"Default Value"},"donotpostalmail":{"value":false,"formatted":"Allow"},"openrevenue_date":{"value":"2019-11-03T20:41:45Z","formatted":"11/3/2019 3:41 PM"},"openrevenue_base":{"value":0,"formatted":"$0.00"},"businesstypecode":{"value":1,"formatted":"Default Value"},"donotemail":{"value":false,"formatted":"Allow"},"address2_shippingmethodcode":{"value":1,"formatted":"Default Value"},"address2_freighttermscode":{"value":1,"formatted":"Default Value"},"createdon":{"value":"2019-03-20T11:32:26Z","formatted":"3/20/2019 7:32 AM"},"opendeals_state":{"value":1,"formatted":"1"},"openrevenue":{"value":0,"formatted":"$0.00"},"donotsendmm":{"value":false,"formatted":"Send"},"donotfax":{"value":false,"formatted":"Allow"},"donotbulkpostalmail":{"value":false,"formatted":"No"},"versionnumber":{"value":4607103,"formatted":"4,607,103"},"creditonhold":{"value":false,"formatted":"No"},"donotbulkemail":{"value":false,"formatted":"Allow"},"followemail":{"value":true,"formatted":"Allow"},"shippingmethodcode":{"value":1,"formatted":"Default Value"},"territorycode":{"value":1,"formatted":"Default Value"},"statuscode":{"value":1,"formatted":"Active"},"participatesinworkflow":{"value":false,"formatted":"No"},"accountclassificationcode":{"value":1,"formatted":"Default Value"},"opendeals_date":{"value":"2019-11-03T20:41:45Z","formatted":"11/3/2019 3:41 PM"},"name":"Helen T. Orcutt","address1_composite":"US","address1_addressid":"542a0b9a-3c98-47b6-9762-b5d18a123069","vm_accountid":"3CA3B8D2-034B-E911-A82F-000D3A17CE77","address1_country":"US","telephone1":"1","accountid":"3ca3b8d2-034b-e911-a82f-000d3a17ce77","address2_addressid":"1881680a-d8cf-457f-981c-63d16bffb3d1","address2_line1":null,"address1_telephone1":null,"address1_postofficebox":null,"marketcap":null,"address1_name":null,"emailaddress3":null,"address1_telephone3":null,"address2_county":null,"numberofemployees":null,"address1_line2":null,"timespentbymeonemailandmeetings":null,"yominame":null,"address2_longitude":null,"ownershipcode":null,"timezoneruleversionnumber":null,"primarysatoriid":null,"_masterid_value":null,"address2_fax":null,"_slaid_value":null,"aging60_base":null,"accountcategorycode":null,"entityimage":null,"revenue":null,"address1_postalcode":null,"emailaddress1":null,"address1_latitude":null,"address1_telephone2":null,"customertypecode":null,"address2_telephone1":null,"address2_name":null,"accountnumber":null,"address1_stateorprovince":null,"address1_line3":null,"industrycode":null,"address1_line1":null,"importsequencenumber":null,"paymenttermscode":null,"fax":null,"address2_line3":null,"address2_utcoffset":null,"_modifiedonbehalfby_value":null,"utcconversiontimezonecode":null,"creditlimit":null,"ftpsiteurl":null,"stockexchange":null,"address2_telephone3":null,"_owningteam_value":null,"aging60":null,"_defaultpricelevelid_value":null,"revenue_base":null,"aging90":null,"aging30":null,"entityimage_url":null,"sharesoutstanding":null,"address2_latitude":null,"stageid":null,"preferredappointmenttimecode":null,"address2_composite":null,"aging90_base":null,"address1_fax":null,"_originatingleadid_value":null,"address1_city":null,"description":null,"address2_stateorprovince":null,"overriddencreatedon":null,"teamsfollowed":null,"_slainvokedid_value":null,"address1_primarycontactname":null,"onholdtime":null,"_createdbyexternalparty_value":null,"traversedpath":null,"processid":null,"_createdonbehalfby_value":null,"_modifiedbyexternalparty_value":null,"address2_postalcode":null,"address1_shippingmethodcode":null,"entityimage_timestamp":null,"address1_upszone":null,"address2_primarycontactname":null,"primarytwitterid":null,"_preferredserviceid_value":null,"address2_city":null,"_primarycontactid_value":null,"address1_freighttermscode":null,"address1_longitude":null,"telephone2":null,"address1_addresstypecode":null,"lastusedincampaign":null,"_preferredsystemuserid_value":null,"address2_postofficebox":null,"creditlimit_base":null,"telephone3":null,"preferredappointmentdaycode":null,"websiteurl":null,"sic":null,"_preferredequipmentid_value":null,"lastonholdtime":null,"address2_line2":null,"tickersymbol":null,"entityimageid":null,"aging30_base":null,"_territoryid_value":null,"address1_county":null,"marketcap_base":null,"address2_upszone":null,"address2_country":null,"address1_utcoffset":null,"emailaddress2":null,"_parentaccountid_value":null,"address2_telephone2":null}`
  );
});

test("FormatObject Format Test", () => {
  const account = {
      "@odata.context":
        "https://valmark.crm.dynamics.com/api/data/v9.0/$metadata#accounts/$entity",
      "@odata.etag": 'W/"4607103"',
      "address2_addresstypecode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      address2_addresstypecode: 1,
      "merged@OData.Community.Display.V1.FormattedValue": "No",
      merged: false,
      "statecode@OData.Community.Display.V1.FormattedValue": "Active",
      statecode: 0,
      "exchangerate@OData.Community.Display.V1.FormattedValue": "1.0000000000",
      exchangerate: 1,
      "openrevenue_state@OData.Community.Display.V1.FormattedValue": "1",
      openrevenue_state: 1,
      name: "Helen T. Orcutt",
      "opendeals@OData.Community.Display.V1.FormattedValue": "1",
      opendeals: 1,
      "modifiedon@OData.Community.Display.V1.FormattedValue":
        "10/18/2019 2:04 PM",
      modifiedon: "2019-10-18T18:04:51Z",
      "_owninguser_value@Microsoft.Dynamics.CRM.lookuplogicalname":
        "systemuser",
      _owninguser_value: "bfd1e1c2-774a-e911-a831-000d3a1a274b",
      address1_composite: "US",
      "accountratingcode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      accountratingcode: 1,
      "marketingonly@OData.Community.Display.V1.FormattedValue": "No",
      marketingonly: false,
      "donotphone@OData.Community.Display.V1.FormattedValue": "Allow",
      donotphone: false,
      "preferredcontactmethodcode@OData.Community.Display.V1.FormattedValue":
        "Any",
      preferredcontactmethodcode: 1,
      "_ownerid_value@OData.Community.Display.V1.FormattedValue": "Rex Tan",
      "_ownerid_value@Microsoft.Dynamics.CRM.associatednavigationproperty":
        "ownerid",
      "_ownerid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      _ownerid_value: "bfd1e1c2-774a-e911-a831-000d3a1a274b",
      "customersizecode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      customersizecode: 1,
      "donotpostalmail@OData.Community.Display.V1.FormattedValue": "Allow",
      donotpostalmail: false,
      "openrevenue_date@OData.Community.Display.V1.FormattedValue":
        "11/3/2019 3:41 PM",
      openrevenue_date: "2019-11-03T20:41:45Z",
      "openrevenue_base@OData.Community.Display.V1.FormattedValue": "$0.00",
      openrevenue_base: 0,
      "businesstypecode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      businesstypecode: 1,
      "donotemail@OData.Community.Display.V1.FormattedValue": "Allow",
      donotemail: false,
      "address2_shippingmethodcode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      address2_shippingmethodcode: 1,
      address1_addressid: "542a0b9a-3c98-47b6-9762-b5d18a123069",
      "address2_freighttermscode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      address2_freighttermscode: 1,
      vm_accountid: "3CA3B8D2-034B-E911-A82F-000D3A17CE77",
      "createdon@OData.Community.Display.V1.FormattedValue":
        "3/20/2019 7:32 AM",
      createdon: "2019-03-20T11:32:26Z",
      "opendeals_state@OData.Community.Display.V1.FormattedValue": "1",
      opendeals_state: 1,
      "openrevenue@OData.Community.Display.V1.FormattedValue": "$0.00",
      openrevenue: 0,
      "donotsendmm@OData.Community.Display.V1.FormattedValue": "Send",
      donotsendmm: false,
      "donotfax@OData.Community.Display.V1.FormattedValue": "Allow",
      donotfax: false,
      "donotbulkpostalmail@OData.Community.Display.V1.FormattedValue": "No",
      donotbulkpostalmail: false,
      address1_country: "US",
      "versionnumber@OData.Community.Display.V1.FormattedValue": "4,607,103",
      versionnumber: 4607103,
      "creditonhold@OData.Community.Display.V1.FormattedValue": "No",
      creditonhold: false,
      telephone1: "1",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue":
        "US Dollar",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty":
        "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname":
        "transactioncurrency",
      _transactioncurrencyid_value: "bf87aaf6-d547-e911-a997-000d3a1abaad",
      accountid: "3ca3b8d2-034b-e911-a82f-000d3a17ce77",
      "donotbulkemail@OData.Community.Display.V1.FormattedValue": "Allow",
      donotbulkemail: false,
      "_modifiedby_value@OData.Community.Display.V1.FormattedValue": "Rex Tan",
      "_modifiedby_value@Microsoft.Dynamics.CRM.lookuplogicalname":
        "systemuser",
      _modifiedby_value: "bfd1e1c2-774a-e911-a831-000d3a1a274b",
      "followemail@OData.Community.Display.V1.FormattedValue": "Allow",
      followemail: true,
      "shippingmethodcode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      shippingmethodcode: 1,
      "_createdby_value@OData.Community.Display.V1.FormattedValue": "Rex Tan",
      "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      _createdby_value: "bfd1e1c2-774a-e911-a831-000d3a1a274b",
      "territorycode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      territorycode: 1,
      "statuscode@OData.Community.Display.V1.FormattedValue": "Active",
      statuscode: 1,
      "participatesinworkflow@OData.Community.Display.V1.FormattedValue": "No",
      participatesinworkflow: false,
      "accountclassificationcode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      accountclassificationcode: 1,
      "_owningbusinessunit_value@Microsoft.Dynamics.CRM.associatednavigationproperty":
        "owningbusinessunit",
      "_owningbusinessunit_value@Microsoft.Dynamics.CRM.lookuplogicalname":
        "businessunit",
      _owningbusinessunit_value: "c25fcf59-ac47-e911-a997-000d3a1abaad",
      address2_addressid: "1881680a-d8cf-457f-981c-63d16bffb3d1",
      "opendeals_date@OData.Community.Display.V1.FormattedValue":
        "11/3/2019 3:41 PM",
      opendeals_date: "2019-11-03T20:41:45Z",
      address2_line1: null,
      address1_telephone1: null,
      address1_postofficebox: null,
      marketcap: null,
      address1_name: null,
      emailaddress3: null,
      address1_telephone3: null,
      address2_county: null,
      numberofemployees: null,
      address1_line2: null,
      timespentbymeonemailandmeetings: null,
      yominame: null,
      address2_longitude: null,
      ownershipcode: null,
      timezoneruleversionnumber: null,
      primarysatoriid: null,
      _masterid_value: null,
      address2_fax: null,
      _slaid_value: null,
      aging60_base: null,
      accountcategorycode: null,
      entityimage: null,
      revenue: null,
      address1_postalcode: null,
      emailaddress1: null,
      address1_latitude: null,
      address1_telephone2: null,
      customertypecode: null,
      address2_telephone1: null,
      address2_name: null,
      accountnumber: null,
      address1_stateorprovince: null,
      address1_line3: null,
      industrycode: null,
      address1_line1: null,
      importsequencenumber: null,
      paymenttermscode: null,
      fax: null,
      address2_line3: null,
      address2_utcoffset: null,
      _modifiedonbehalfby_value: null,
      utcconversiontimezonecode: null,
      creditlimit: null,
      ftpsiteurl: null,
      stockexchange: null,
      address2_telephone3: null,
      _owningteam_value: null,
      aging60: null,
      _defaultpricelevelid_value: null,
      revenue_base: null,
      aging90: null,
      aging30: null,
      entityimage_url: null,
      sharesoutstanding: null,
      address2_latitude: null,
      stageid: null,
      preferredappointmenttimecode: null,
      address2_composite: null,
      aging90_base: null,
      address1_fax: null,
      _originatingleadid_value: null,
      address1_city: null,
      description: null,
      address2_stateorprovince: null,
      overriddencreatedon: null,
      teamsfollowed: null,
      _slainvokedid_value: null,
      address1_primarycontactname: null,
      onholdtime: null,
      _createdbyexternalparty_value: null,
      traversedpath: null,
      processid: null,
      _createdonbehalfby_value: null,
      _modifiedbyexternalparty_value: null,
      address2_postalcode: null,
      address1_shippingmethodcode: null,
      entityimage_timestamp: null,
      address1_upszone: null,
      address2_primarycontactname: null,
      primarytwitterid: null,
      _preferredserviceid_value: null,
      address2_city: null,
      _primarycontactid_value: null,
      address1_freighttermscode: null,
      address1_longitude: null,
      telephone2: null,
      address1_addresstypecode: null,
      lastusedincampaign: null,
      _preferredsystemuserid_value: null,
      address2_postofficebox: null,
      creditlimit_base: null,
      telephone3: null,
      preferredappointmentdaycode: null,
      websiteurl: null,
      sic: null,
      _preferredequipmentid_value: null,
      lastonholdtime: null,
      address2_line2: null,
      tickersymbol: null,
      entityimageid: null,
      aging30_base: null,
      _territoryid_value: null,
      address1_county: null,
      marketcap_base: null,
      address2_upszone: null,
      address2_country: null,
      address1_utcoffset: null,
      emailaddress2: null,
      _parentaccountid_value: null,
      address2_telephone2: null
    },
    newAccount = formatObject(account, FormatValue.formatOnly);

  expect(JSON.stringify(newAccount)).toBe(
    `{"ownerid":"Rex Tan","transactioncurrencyid":"US Dollar","modifiedby":"Rex Tan","createdby":"Rex Tan","address2_addresstypecode":"Default Value","merged":"No","statecode":"Active","exchangerate":"1.0000000000","openrevenue_state":"1","opendeals":"1","modifiedon":"10/18/2019 2:04 PM","accountratingcode":"Default Value","marketingonly":"No","donotphone":"Allow","preferredcontactmethodcode":"Any","customersizecode":"Default Value","donotpostalmail":"Allow","openrevenue_date":"11/3/2019 3:41 PM","openrevenue_base":"$0.00","businesstypecode":"Default Value","donotemail":"Allow","address2_shippingmethodcode":"Default Value","address2_freighttermscode":"Default Value","createdon":"3/20/2019 7:32 AM","opendeals_state":"1","openrevenue":"$0.00","donotsendmm":"Send","donotfax":"Allow","donotbulkpostalmail":"No","versionnumber":"4,607,103","creditonhold":"No","donotbulkemail":"Allow","followemail":"Allow","shippingmethodcode":"Default Value","territorycode":"Default Value","statuscode":"Active","participatesinworkflow":"No","accountclassificationcode":"Default Value","opendeals_date":"11/3/2019 3:41 PM","name":"Helen T. Orcutt","address1_composite":"US","address1_addressid":"542a0b9a-3c98-47b6-9762-b5d18a123069","vm_accountid":"3CA3B8D2-034B-E911-A82F-000D3A17CE77","address1_country":"US","telephone1":"1","accountid":"3ca3b8d2-034b-e911-a82f-000d3a17ce77","address2_addressid":"1881680a-d8cf-457f-981c-63d16bffb3d1","address2_line1":null,"address1_telephone1":null,"address1_postofficebox":null,"marketcap":null,"address1_name":null,"emailaddress3":null,"address1_telephone3":null,"address2_county":null,"numberofemployees":null,"address1_line2":null,"timespentbymeonemailandmeetings":null,"yominame":null,"address2_longitude":null,"ownershipcode":null,"timezoneruleversionnumber":null,"primarysatoriid":null,"_masterid_value":null,"address2_fax":null,"_slaid_value":null,"aging60_base":null,"accountcategorycode":null,"entityimage":null,"revenue":null,"address1_postalcode":null,"emailaddress1":null,"address1_latitude":null,"address1_telephone2":null,"customertypecode":null,"address2_telephone1":null,"address2_name":null,"accountnumber":null,"address1_stateorprovince":null,"address1_line3":null,"industrycode":null,"address1_line1":null,"importsequencenumber":null,"paymenttermscode":null,"fax":null,"address2_line3":null,"address2_utcoffset":null,"_modifiedonbehalfby_value":null,"utcconversiontimezonecode":null,"creditlimit":null,"ftpsiteurl":null,"stockexchange":null,"address2_telephone3":null,"_owningteam_value":null,"aging60":null,"_defaultpricelevelid_value":null,"revenue_base":null,"aging90":null,"aging30":null,"entityimage_url":null,"sharesoutstanding":null,"address2_latitude":null,"stageid":null,"preferredappointmenttimecode":null,"address2_composite":null,"aging90_base":null,"address1_fax":null,"_originatingleadid_value":null,"address1_city":null,"description":null,"address2_stateorprovince":null,"overriddencreatedon":null,"teamsfollowed":null,"_slainvokedid_value":null,"address1_primarycontactname":null,"onholdtime":null,"_createdbyexternalparty_value":null,"traversedpath":null,"processid":null,"_createdonbehalfby_value":null,"_modifiedbyexternalparty_value":null,"address2_postalcode":null,"address1_shippingmethodcode":null,"entityimage_timestamp":null,"address1_upszone":null,"address2_primarycontactname":null,"primarytwitterid":null,"_preferredserviceid_value":null,"address2_city":null,"_primarycontactid_value":null,"address1_freighttermscode":null,"address1_longitude":null,"telephone2":null,"address1_addresstypecode":null,"lastusedincampaign":null,"_preferredsystemuserid_value":null,"address2_postofficebox":null,"creditlimit_base":null,"telephone3":null,"preferredappointmentdaycode":null,"websiteurl":null,"sic":null,"_preferredequipmentid_value":null,"lastonholdtime":null,"address2_line2":null,"tickersymbol":null,"entityimageid":null,"aging30_base":null,"_territoryid_value":null,"address1_county":null,"marketcap_base":null,"address2_upszone":null,"address2_country":null,"address1_utcoffset":null,"emailaddress2":null,"_parentaccountid_value":null,"address2_telephone2":null}`
  );
});

test("FormatObject Value Test", () => {
  const account = {
      "@odata.context":
        "https://valmark.crm.dynamics.com/api/data/v9.0/$metadata#accounts/$entity",
      "@odata.etag": 'W/"4607103"',
      "address2_addresstypecode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      address2_addresstypecode: 1,
      "merged@OData.Community.Display.V1.FormattedValue": "No",
      merged: false,
      "statecode@OData.Community.Display.V1.FormattedValue": "Active",
      statecode: 0,
      "exchangerate@OData.Community.Display.V1.FormattedValue": "1.0000000000",
      exchangerate: 1,
      "openrevenue_state@OData.Community.Display.V1.FormattedValue": "1",
      openrevenue_state: 1,
      name: "Helen T. Orcutt",
      "opendeals@OData.Community.Display.V1.FormattedValue": "1",
      opendeals: 1,
      "modifiedon@OData.Community.Display.V1.FormattedValue":
        "10/18/2019 2:04 PM",
      modifiedon: "2019-10-18T18:04:51Z",
      "_owninguser_value@Microsoft.Dynamics.CRM.lookuplogicalname":
        "systemuser",
      _owninguser_value: "bfd1e1c2-774a-e911-a831-000d3a1a274b",
      address1_composite: "US",
      "accountratingcode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      accountratingcode: 1,
      "marketingonly@OData.Community.Display.V1.FormattedValue": "No",
      marketingonly: false,
      "donotphone@OData.Community.Display.V1.FormattedValue": "Allow",
      donotphone: false,
      "preferredcontactmethodcode@OData.Community.Display.V1.FormattedValue":
        "Any",
      preferredcontactmethodcode: 1,
      "_ownerid_value@OData.Community.Display.V1.FormattedValue": "Rex Tan",
      "_ownerid_value@Microsoft.Dynamics.CRM.associatednavigationproperty":
        "ownerid",
      "_ownerid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      _ownerid_value: "bfd1e1c2-774a-e911-a831-000d3a1a274b",
      "customersizecode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      customersizecode: 1,
      "donotpostalmail@OData.Community.Display.V1.FormattedValue": "Allow",
      donotpostalmail: false,
      "openrevenue_date@OData.Community.Display.V1.FormattedValue":
        "11/3/2019 3:41 PM",
      openrevenue_date: "2019-11-03T20:41:45Z",
      "openrevenue_base@OData.Community.Display.V1.FormattedValue": "$0.00",
      openrevenue_base: 0,
      "businesstypecode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      businesstypecode: 1,
      "donotemail@OData.Community.Display.V1.FormattedValue": "Allow",
      donotemail: false,
      "address2_shippingmethodcode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      address2_shippingmethodcode: 1,
      address1_addressid: "542a0b9a-3c98-47b6-9762-b5d18a123069",
      "address2_freighttermscode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      address2_freighttermscode: 1,
      vm_accountid: "3CA3B8D2-034B-E911-A82F-000D3A17CE77",
      "createdon@OData.Community.Display.V1.FormattedValue":
        "3/20/2019 7:32 AM",
      createdon: "2019-03-20T11:32:26Z",
      "opendeals_state@OData.Community.Display.V1.FormattedValue": "1",
      opendeals_state: 1,
      "openrevenue@OData.Community.Display.V1.FormattedValue": "$0.00",
      openrevenue: 0,
      "donotsendmm@OData.Community.Display.V1.FormattedValue": "Send",
      donotsendmm: false,
      "donotfax@OData.Community.Display.V1.FormattedValue": "Allow",
      donotfax: false,
      "donotbulkpostalmail@OData.Community.Display.V1.FormattedValue": "No",
      donotbulkpostalmail: false,
      address1_country: "US",
      "versionnumber@OData.Community.Display.V1.FormattedValue": "4,607,103",
      versionnumber: 4607103,
      "creditonhold@OData.Community.Display.V1.FormattedValue": "No",
      creditonhold: false,
      telephone1: "1",
      "_transactioncurrencyid_value@OData.Community.Display.V1.FormattedValue":
        "US Dollar",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.associatednavigationproperty":
        "transactioncurrencyid",
      "_transactioncurrencyid_value@Microsoft.Dynamics.CRM.lookuplogicalname":
        "transactioncurrency",
      _transactioncurrencyid_value: "bf87aaf6-d547-e911-a997-000d3a1abaad",
      accountid: "3ca3b8d2-034b-e911-a82f-000d3a17ce77",
      "donotbulkemail@OData.Community.Display.V1.FormattedValue": "Allow",
      donotbulkemail: false,
      "_modifiedby_value@OData.Community.Display.V1.FormattedValue": "Rex Tan",
      "_modifiedby_value@Microsoft.Dynamics.CRM.lookuplogicalname":
        "systemuser",
      _modifiedby_value: "bfd1e1c2-774a-e911-a831-000d3a1a274b",
      "followemail@OData.Community.Display.V1.FormattedValue": "Allow",
      followemail: true,
      "shippingmethodcode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      shippingmethodcode: 1,
      "_createdby_value@OData.Community.Display.V1.FormattedValue": "Rex Tan",
      "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      _createdby_value: "bfd1e1c2-774a-e911-a831-000d3a1a274b",
      "territorycode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      territorycode: 1,
      "statuscode@OData.Community.Display.V1.FormattedValue": "Active",
      statuscode: 1,
      "participatesinworkflow@OData.Community.Display.V1.FormattedValue": "No",
      participatesinworkflow: false,
      "accountclassificationcode@OData.Community.Display.V1.FormattedValue":
        "Default Value",
      accountclassificationcode: 1,
      "_owningbusinessunit_value@Microsoft.Dynamics.CRM.associatednavigationproperty":
        "owningbusinessunit",
      "_owningbusinessunit_value@Microsoft.Dynamics.CRM.lookuplogicalname":
        "businessunit",
      _owningbusinessunit_value: "c25fcf59-ac47-e911-a997-000d3a1abaad",
      address2_addressid: "1881680a-d8cf-457f-981c-63d16bffb3d1",
      "opendeals_date@OData.Community.Display.V1.FormattedValue":
        "11/3/2019 3:41 PM",
      opendeals_date: "2019-11-03T20:41:45Z",
      address2_line1: null,
      address1_telephone1: null,
      address1_postofficebox: null,
      marketcap: null,
      address1_name: null,
      emailaddress3: null,
      address1_telephone3: null,
      address2_county: null,
      numberofemployees: null,
      address1_line2: null,
      timespentbymeonemailandmeetings: null,
      yominame: null,
      address2_longitude: null,
      ownershipcode: null,
      timezoneruleversionnumber: null,
      primarysatoriid: null,
      _masterid_value: null,
      address2_fax: null,
      _slaid_value: null,
      aging60_base: null,
      accountcategorycode: null,
      entityimage: null,
      revenue: null,
      address1_postalcode: null,
      emailaddress1: null,
      address1_latitude: null,
      address1_telephone2: null,
      customertypecode: null,
      address2_telephone1: null,
      address2_name: null,
      accountnumber: null,
      address1_stateorprovince: null,
      address1_line3: null,
      industrycode: null,
      address1_line1: null,
      importsequencenumber: null,
      paymenttermscode: null,
      fax: null,
      address2_line3: null,
      address2_utcoffset: null,
      _modifiedonbehalfby_value: null,
      utcconversiontimezonecode: null,
      creditlimit: null,
      ftpsiteurl: null,
      stockexchange: null,
      address2_telephone3: null,
      _owningteam_value: null,
      aging60: null,
      _defaultpricelevelid_value: null,
      revenue_base: null,
      aging90: null,
      aging30: null,
      entityimage_url: null,
      sharesoutstanding: null,
      address2_latitude: null,
      stageid: null,
      preferredappointmenttimecode: null,
      address2_composite: null,
      aging90_base: null,
      address1_fax: null,
      _originatingleadid_value: null,
      address1_city: null,
      description: null,
      address2_stateorprovince: null,
      overriddencreatedon: null,
      teamsfollowed: null,
      _slainvokedid_value: null,
      address1_primarycontactname: null,
      onholdtime: null,
      _createdbyexternalparty_value: null,
      traversedpath: null,
      processid: null,
      _createdonbehalfby_value: null,
      _modifiedbyexternalparty_value: null,
      address2_postalcode: null,
      address1_shippingmethodcode: null,
      entityimage_timestamp: null,
      address1_upszone: null,
      address2_primarycontactname: null,
      primarytwitterid: null,
      _preferredserviceid_value: null,
      address2_city: null,
      _primarycontactid_value: null,
      address1_freighttermscode: null,
      address1_longitude: null,
      telephone2: null,
      address1_addresstypecode: null,
      lastusedincampaign: null,
      _preferredsystemuserid_value: null,
      address2_postofficebox: null,
      creditlimit_base: null,
      telephone3: null,
      preferredappointmentdaycode: null,
      websiteurl: null,
      sic: null,
      _preferredequipmentid_value: null,
      lastonholdtime: null,
      address2_line2: null,
      tickersymbol: null,
      entityimageid: null,
      aging30_base: null,
      _territoryid_value: null,
      address1_county: null,
      marketcap_base: null,
      address2_upszone: null,
      address2_country: null,
      address1_utcoffset: null,
      emailaddress2: null,
      _parentaccountid_value: null,
      address2_telephone2: null
    },
    newAccount = formatObject(account, FormatValue.valueOnly);

  expect(JSON.stringify(newAccount)).toBe(
    `{\"owninguser\":\"bfd1e1c2-774a-e911-a831-000d3a1a274b\",\"ownerid\":\"bfd1e1c2-774a-e911-a831-000d3a1a274b\",\"transactioncurrencyid\":\"bf87aaf6-d547-e911-a997-000d3a1abaad\",\"modifiedby\":\"bfd1e1c2-774a-e911-a831-000d3a1a274b\",\"createdby\":\"bfd1e1c2-774a-e911-a831-000d3a1a274b\",\"owningbusinessunit\":\"c25fcf59-ac47-e911-a997-000d3a1abaad\",\"address2_addresstypecode\":1,\"merged\":false,\"statecode\":0,\"exchangerate\":1,\"openrevenue_state\":1,\"opendeals\":1,\"modifiedon\":\"2019-10-18T18:04:51Z\",\"accountratingcode\":1,\"marketingonly\":false,\"donotphone\":false,\"preferredcontactmethodcode\":1,\"customersizecode\":1,\"donotpostalmail\":false,\"openrevenue_date\":\"2019-11-03T20:41:45Z\",\"openrevenue_base\":0,\"businesstypecode\":1,\"donotemail\":false,\"address2_shippingmethodcode\":1,\"address2_freighttermscode\":1,\"createdon\":\"2019-03-20T11:32:26Z\",\"opendeals_state\":1,\"openrevenue\":0,\"donotsendmm\":false,\"donotfax\":false,\"donotbulkpostalmail\":false,\"versionnumber\":4607103,\"creditonhold\":false,\"donotbulkemail\":false,\"followemail\":true,\"shippingmethodcode\":1,\"territorycode\":1,\"statuscode\":1,\"participatesinworkflow\":false,\"accountclassificationcode\":1,\"opendeals_date\":\"2019-11-03T20:41:45Z\",\"name\":\"Helen T. Orcutt\",\"address1_composite\":\"US\",\"address1_addressid\":\"542a0b9a-3c98-47b6-9762-b5d18a123069\",\"vm_accountid\":\"3CA3B8D2-034B-E911-A82F-000D3A17CE77\",\"address1_country\":\"US\",\"telephone1\":\"1\",\"accountid\":\"3ca3b8d2-034b-e911-a82f-000d3a17ce77\",\"address2_addressid\":\"1881680a-d8cf-457f-981c-63d16bffb3d1\",\"address2_line1\":null,\"address1_telephone1\":null,\"address1_postofficebox\":null,\"marketcap\":null,\"address1_name\":null,\"emailaddress3\":null,\"address1_telephone3\":null,\"address2_county\":null,\"numberofemployees\":null,\"address1_line2\":null,\"timespentbymeonemailandmeetings\":null,\"yominame\":null,\"address2_longitude\":null,\"ownershipcode\":null,\"timezoneruleversionnumber\":null,\"primarysatoriid\":null,\"_masterid_value\":null,\"address2_fax\":null,\"_slaid_value\":null,\"aging60_base\":null,\"accountcategorycode\":null,\"entityimage\":null,\"revenue\":null,\"address1_postalcode\":null,\"emailaddress1\":null,\"address1_latitude\":null,\"address1_telephone2\":null,\"customertypecode\":null,\"address2_telephone1\":null,\"address2_name\":null,\"accountnumber\":null,\"address1_stateorprovince\":null,\"address1_line3\":null,\"industrycode\":null,\"address1_line1\":null,\"importsequencenumber\":null,\"paymenttermscode\":null,\"fax\":null,\"address2_line3\":null,\"address2_utcoffset\":null,\"_modifiedonbehalfby_value\":null,\"utcconversiontimezonecode\":null,\"creditlimit\":null,\"ftpsiteurl\":null,\"stockexchange\":null,\"address2_telephone3\":null,\"_owningteam_value\":null,\"aging60\":null,\"_defaultpricelevelid_value\":null,\"revenue_base\":null,\"aging90\":null,\"aging30\":null,\"entityimage_url\":null,\"sharesoutstanding\":null,\"address2_latitude\":null,\"stageid\":null,\"preferredappointmenttimecode\":null,\"address2_composite\":null,\"aging90_base\":null,\"address1_fax\":null,\"_originatingleadid_value\":null,\"address1_city\":null,\"description\":null,\"address2_stateorprovince\":null,\"overriddencreatedon\":null,\"teamsfollowed\":null,\"_slainvokedid_value\":null,\"address1_primarycontactname\":null,\"onholdtime\":null,\"_createdbyexternalparty_value\":null,\"traversedpath\":null,\"processid\":null,\"_createdonbehalfby_value\":null,\"_modifiedbyexternalparty_value\":null,\"address2_postalcode\":null,\"address1_shippingmethodcode\":null,\"entityimage_timestamp\":null,\"address1_upszone\":null,\"address2_primarycontactname\":null,\"primarytwitterid\":null,\"_preferredserviceid_value\":null,\"address2_city\":null,\"_primarycontactid_value\":null,\"address1_freighttermscode\":null,\"address1_longitude\":null,\"telephone2\":null,\"address1_addresstypecode\":null,\"lastusedincampaign\":null,\"_preferredsystemuserid_value\":null,\"address2_postofficebox\":null,\"creditlimit_base\":null,\"telephone3\":null,\"preferredappointmentdaycode\":null,\"websiteurl\":null,\"sic\":null,\"_preferredequipmentid_value\":null,\"lastonholdtime\":null,\"address2_line2\":null,\"tickersymbol\":null,\"entityimageid\":null,\"aging30_base\":null,\"_territoryid_value\":null,\"address1_county\":null,\"marketcap_base\":null,\"address2_upszone\":null,\"address2_country\":null,\"address1_utcoffset\":null,\"emailaddress2\":null,\"_parentaccountid_value\":null,\"address2_telephone2\":null}`
  );
});
